# Generated by Django 3.1.7 on 2022-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_bill',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(max_length=10)),
                ('storage_id', models.CharField(max_length=10)),
                ('supplier_id', models.CharField(max_length=10)),
                ('goods_price', models.CharField(max_length=12)),
                ('goods_num', models.CharField(max_length=10)),
                ('entry_data', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=10)),
                ('goods_sort', models.CharField(max_length=10)),
                ('goods_num', models.CharField(max_length=10)),
                ('goods_remark', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='out_bill',
            fields=[
                ('out_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(max_length=10)),
                ('storage_id', models.CharField(max_length=10)),
                ('subscriber_id', models.CharField(max_length=10)),
                ('goods_price', models.CharField(max_length=10)),
                ('goods_num', models.CharField(max_length=10)),
                ('out_data', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancel_reason',
            name='task',
        ),
        migrations.RemoveField(
            model_name='cancel_reason',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='discussant',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='task',
        ),
        migrations.DeleteModel(
            name='MainWheel',
        ),
        migrations.RemoveField(
            model_name='response',
            name='discuss',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='revoke_reason',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact_type_hunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact_type_publisher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='Cancel_reason',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Revoke_reason',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
