# Generated by Django 3.1.7 on 2022-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20220526_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('repassword', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('icon', models.ImageField(default='icons/haha.jpg', null=True, upload_to='icons/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('tel', models.PositiveIntegerField(blank=True, null=True)),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, max_length=20, null=True)),
                ('other', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'smh_user',
            },
        ),
    ]
