# Generated by Django 3.1.7 on 2022-05-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('materials_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('materials_int', models.IntegerField()),
                ('materials_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('password_c', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('recipients', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=11)),
                ('addressee_p', models.CharField(default='', max_length=6)),
                ('direction', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=256)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_req_time', models.DateTimeField()),
                ('materials_req_int', models.IntegerField()),
                ('materials_text', models.TextField()),
                ('materials_time', models.DateTimeField(auto_now_add=True)),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('o_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('o_date', models.DateTimeField(auto_now=True)),
                ('o_pay', models.BooleanField(default=False)),
                ('o_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('o_address', models.CharField(max_length=150)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_img', models.ImageField(upload_to='shop')),
                ('g_num', models.CharField(max_length=100)),
                ('g_price', models.FloatField(default=0)),
                ('g_unit', models.CharField(default='500g', max_length=20)),
                ('g_repertory', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.articlecategory')),
            ],
        ),
    ]
