# Generated by Django 3.1.7 on 2022-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.goodsvalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.usermodel')),
            ],
            options={
                'db_table': 'sx_cart',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('isTrue', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.goodsvalue')),
            ],
            options={
                'db_table': 'sx_order_detail',
            },
        ),
        migrations.RemoveField(
            model_name='requests',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='user',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='sx_order',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.ordermodel'),
        ),
    ]
