# Generated by Django 3.1.7 on 2022-05-26 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_auto_20220526_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUserModel',
        ),
        migrations.RemoveField(
            model_name='userticketmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goodsvalue',
            name='g_price',
        ),
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='o_pay',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='o_total',
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='o_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='cartinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderdetailmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='UserTicketModel',
        ),
    ]
